// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("Persimmon.Dried")>]
[<assembly: AssemblyProductAttribute("Persimmon.Dried")>]
[<assembly: InternalsVisibleToAttribute("Persimmon.Dried.Tests")>]
[<assembly: AssemblyVersionAttribute("4.0.0")>]
[<assembly: AssemblyFileVersionAttribute("4.0.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Persimmon.Dried"
    let [<Literal>] AssemblyProduct = "Persimmon.Dried"
    let [<Literal>] InternalsVisibleTo = "Persimmon.Dried.Tests"
    let [<Literal>] AssemblyVersion = "4.0.0"
    let [<Literal>] AssemblyFileVersion = "4.0.0"
    let [<Literal>] AssemblyConfiguration = "Release"
