language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      mono: latest
      dotnet: 2.1.4

before_script:
 - chmod +x ./build.sh
script:
  - ./build.sh

cache:
  directories:
    - paket-files
    - packages
