// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Persimmon.Dried.Gen")>]
[<assembly: AssemblyProductAttribute("Persimmon.Dried")>]
[<assembly: AssemblyVersionAttribute("3.0.0")>]
[<assembly: AssemblyFileVersionAttribute("3.0.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Persimmon.Dried.Gen"
    let [<Literal>] AssemblyProduct = "Persimmon.Dried"
    let [<Literal>] AssemblyVersion = "3.0.0"
    let [<Literal>] AssemblyFileVersion = "3.0.0"
    let [<Literal>] AssemblyConfiguration = "Release"
