// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Persimmon.Dried.Gen")>]
[<assembly: AssemblyProductAttribute("Persimmon.Dried")>]
[<assembly: AssemblyVersionAttribute("4.0.1")>]
[<assembly: AssemblyFileVersionAttribute("4.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Persimmon.Dried.Gen"
    let [<Literal>] AssemblyProduct = "Persimmon.Dried"
    let [<Literal>] AssemblyVersion = "4.0.1"
    let [<Literal>] AssemblyFileVersion = "4.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
